agenda/urls.py
from django.urls import path

from .views import PDFView, AgendaDetailView, VisitaGuiadaView, RutaView, ICSAgenda, DescargarPlaylist, GenerarRSS, AlojamientoView, RestauranteView, TurismeSostenibleView



app_name = 'agenda'

urlpatterns = [
    path('calendario/', PDFView.as_view(), name= 'calendario_pdf'),
    path('ics/', ICSAgenda.as_view(), name= 'agenda_ics'),
    path('descargar-playlist/', DescargarPlaylist.as_view(), name= 'descargar-audio'),
    path('visites-guiades/<slug:slug>/', VisitaGuiadaView.as_view(), name= 'visites-guiades'),
    path('ruta/<slug:slug>/', RutaView.as_view(), name= 'ruta'),
    path('descargar-playlist-rss/',GenerarRSS.as_view(), name= 'descargar-audio-rss'),
    path('allotjament/<slug:slug>/', AlojamientoView.as_view(), name= 'allotjament'),
    path('restaurant/<slug:slug>/', RestauranteView.as_view(), name="restaurant"),
    path('sostenibilitat/<slug:slug>/', TurismeSostenibleView.as_view(), name="turisme_sostenible"),
    path('<slug:slug>/', AgendaDetailView.as_view(), name= 'detalle_agenda'),
]

api/urls.py
from django.urls import path
from .views import TeenvioView
app_name = 'api'
urlpatterns = [
        path('newsletter/', TeenvioView.as_view(), name='newsletter'),
]

blog/urls.py
from django.urls import path
from .views import ListarPostsView, DetallePostView, ListarCategoria, ListarSubBlogView,DetalleSubBlogView, CategoriaDetailView, FiltrarAgendaView, DetalleNoticiaView, ListarNoticiaView, SubCategoriaDetailView, RestaurantAPI


app_name = 'blog'

urlpatterns = [
    path('posts/', ListarPostsView.as_view(), name='listar_posts'),
    path('post/<slug:slug>/', DetallePostView.as_view(), name='detalle_post'),
    path('categorias/', ListarCategoria.as_view(),name='listar_categoria'),
    path('c/<slug:slug>/', CategoriaDetailView.as_view(), name='categoria'),
    path('subblog/<slug:slug>/', DetalleSubBlogView.as_view(), name='detalle-subblog'),
    # API endpoints
    path('api/filtrar-agenda/', FiltrarAgendaView.as_view(), name='filtrar_agenda_api'),
    path('api/filtrar-restaurante/', RestaurantAPI.as_view(), name='filtrar_restaurante'),
    path('noticies/', ListarNoticiaView.as_view(), name="noticies"),
    path('n/<slug:slug>/', DetalleNoticiaView.as_view(), name='noticia'),
    path('subcategoria/<slug:slug>/', SubCategoriaDetailView.as_view(), name='subcategoria')
]

gaudeix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from multimedia_manager.urls import urlpatterns as url_media
#from multimedia_manager.filters import ImagenAutocomplete
from django.urls import re_path
from django_select2 import urls as select2_urls

from django.urls import path
from django.views.i18n import set_language

urlpatterns = [

    path('admin_gaudeix/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('',include('blog.urls')),
    path('agenda/',include('agenda.urls')),
    path('map/',include('map.urls')),
    path('',include('personalizacion.urls')),
    path('', include('paginas_estaticas.urls')),
    path('s/', include('eventos_especiales.urls')),
    path('api/', include('api.urls')),
    path('sv/',include('subvenciones.urls')),
    path('c-d/', include('compra_y_descubre.urls')),
    path('idiomes/', include('django.conf.urls.i18n')),
    path('', include('traducciones.urls')),
    # re_path(
    #     r'^imagen-autocomplete/$',
    #     ImagenAutocomplete.as_view(),
    #     name='imagen-autocomplete',
    # ),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

map/urls.py
from django.urls import path
from .views import CoordenadasAyuntamientoAPI,MapPointAPI, MapaView

app_name= 'map'

urlpatterns = [
        path('api/coordenadas-ayuntamiento/', CoordenadasAyuntamientoAPI.as_view(), name='coordenadas_ayuntamiento_api'),
        path('api/map-points/', MapPointAPI.as_view(), name='map_points_api'),
        path('<slug:slug>/', MapaView.as_view(), name='mapa')
]

selecciones/models.py
from django.db import models
from blog.models import Post
from eventos_especiales.models import EventoEspecial
# Create your models here.

class SeleccionDestacados(models.Model):
    
    titulo = models.CharField(
        max_length=100,
        help_text="Escriu un nom únic",
        verbose_name="Títol"
    )
    publicado = models.BooleanField(
        default=False,
        help_text="Marca si vols que estigui despublicat.",
        verbose_name="Publicat"
    )
    coleccion = models.ManyToManyField(
        Post,
        related_name='seleccions',
        blank=True,
        verbose_name="colecció"
    )
    eventos_especiales = models.ManyToManyField(
        EventoEspecial,
        related_name="seleccio_especial",
        blank=True,
        help_text="Selecciona els esdeveniments que vols que apareguin a la portada."
    )

    def __str__(self):
        return self.titulo

selecciones/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from blog.models import Post
from eventos_especiales.models import EventoEspecial
from.models import SeleccionDestacados

class SeleccionForm(forms.ModelForm):
    coleccion = forms.ModelMultipleChoiceField(
        queryset=Post.objects.all(),
        widget=FilteredSelectMultiple('Posts', is_stacked=False),
        required=False,
        label='Posts'
    )

    class Meta:
        model = SeleccionDestacados
        fields = '__all__'

def save_model(self, request, obj, form, change):
    # Guardar el objeto SeleccionDestacados
    obj.save()

    # Obtener los posts seleccionados del formulario
    posts = form.cleaned_data['coleccion']

    # Eliminar todas las relaciones de posts existentes
    obj.posts.clear()

    # Agregar los posts seleccionados a la selección destacada
    obj.posts.set(posts)

    # Guardar la selección destacada con las relaciones actualizadas
    obj.save()

agenda/views.py
from .models import Agenda, VisitaGuiada, Ruta, VariationAgenda, Idioma, AudioRuta, PlayListRuta, Alojamiento, Restaurante, TurismeSostenible
from blog.models import Post
from django.views import View
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from xhtml2pdf import pisa
from django.template.loader import get_template
from io import BytesIO
from django.db.models import Q, Max
from datetime import datetime, timedelta, time
from core.mixin.base import BaseContextMixin
from django.utils import timezone
import itertools
import emoji
import re
import os
from blog.models import Categoria
from personalizacion.models import Personalizacion
from gaudeix.settings import DOMAIN_URL
from icalendar import Calendar, Event as iCalEvent
from io import BytesIO
from django.http import HttpResponse
from django.urls import reverse
from gaudeix import settings
from django.http import JsonResponse
from xml.etree import ElementTree as ET
from django.utils.translation import get_language_from_request

from gaudeix.settings import NOMBRES_MESES, NOMBRES_DIAS


class TurismeSostenibleView(BaseContextMixin, DetailView):
    model = TurismeSostenible
    template_name = 'agenda/turisme_sostenible.html'
    context_object_name = 'turisme_sostenible'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # current_object = self.get_object()  # Esta línea es redundante.

        return context


class RestauranteView(BaseContextMixin, DetailView):
    model = Restaurante
    template_name = 'agenda/restaurante.html'
    context_object_name = 'restaurante'



    def get_object(self, queryset=None):
        # Obtener el objeto de la agenda utilizando el slug en lugar del ID
        
        slug = self.kwargs.get('slug')
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset, slug=slug)
        return obj
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # current_object = self.get_object()  # Esta línea es redundante.
        restaurantes = Restaurante.objects.filter(publicado=True).exclude(pk=self.object.pk)

        # Verificar si hay al menos 4 alojamientos para evitar errores
        if restaurantes.count() > 4:
            restaurantes = restaurantes.order_by('?')[:4]
        else:
            restaurantes = restaurantes.order_by('-fecha_creacion')[:4]  # O cualquier otro criterio

        context['coleccion_destacados'] = restaurantes

        return context




    def get_object(self, queryset=None):
        # Obtener el objeto de la agenda utilizando el slug en lugar del ID
        
        slug = self.kwargs.get('slug')
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset, slug=slug)
        return obj
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # current_object = self.get_object()  # Esta línea es redundante.
        restaurantes = Restaurante.objects.filter(publicado=True).exclude(pk=self.object.pk)

        # Verificar si hay al menos 4 alojamientos para evitar errores
        if restaurantes.count() > 4:
            restaurantes = restaurantes.order_by('?')[:4]
        else:
            restaurantes = restaurantes.order_by('-fecha_creacion')[:4]  # O cualquier otro criterio

        context['coleccion_destacados'] = restaurantes

        return context


class AlojamientoView(BaseContextMixin, DetailView):

    model = Alojamiento
    template_name = 'agenda/alojamiento.html'
    context_object_name = 'alojamiento'



    def get_object(self, queryset=None):
        # Obtener el objeto de la agenda utilizando el slug en lugar del ID
        
        slug = self.kwargs.get('slug')
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset, slug=slug)
        return obj
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # current_object = self.get_object()  # Esta línea es redundante.
        alojamientos = Alojamiento.objects.filter(publicado=True).exclude(pk=self.object.pk)

        # Verificar si hay al menos 4 alojamientos para evitar errores
        if alojamientos.count() > 4:
            alojamientos = alojamientos.order_by('?')[:4]
        else:
            alojamientos = alojamientos.order_by('-fecha_creacion')[:4]  # O cualquier otro criterio

        context['coleccion_destacados'] = alojamientos

        return context




class VisitaGuiadaView(BaseContextMixin, DetailView):
    model = VisitaGuiada
    template_name = 'agenda/visita_guiada.html'
    context_object_name = 'visites'



    def get_object(self, queryset=None):
        # Obtener el objeto de la agenda utilizando el slug en lugar del ID
        
        slug = self.kwargs.get('slug')
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset, slug=slug)
        return obj
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_object = self.get_object()

       
        visita_guiadas = VisitaGuiada.objects.filter(publicado=True).exclude(pk=current_object.pk)
        categorias = Categoria.objects.filter(publicado= True).all()

        fechas = [fecha.fecha.strftime("%Y-%m-%d") for fecha in current_object.fechas.all()]
        #print("Agendas Relacionadas:", agendas_relacionadas)

        context['coleccion_destacados'] = visita_guiadas
        context['categorias'] = categorias
        context['agendas_relacionadas'] = current_object.agendas.all()
        context['fechas_json'] = fechas
        return context

class RutaView(BaseContextMixin, DetailView):
    model = Ruta
    template_name = 'agenda/ruta.html'
    context_object_name = 'ruta'

    def get_object(self, queryset=None):
        # Obtener el objeto de la agenda utilizando el slug en lugar del ID
        
        slug = self.kwargs.get('slug')
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset, slug=slug)
        return obj
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_object = self.get_object()
        # Obtener los puntos de itinerario ordenados alfabéticamente
        puntos_itinerario = current_object.mapas_itinerario.all().order_by('titulo')
        rutes = Ruta.objects.filter(publicado = True).exclude(pk = current_object.pk)
        now = timezone.now()
        ultimos_post = Agenda.objects.filter(publicado = True)[:4]
        idiomas = Idioma.objects.filter()

        context['rutes'] = rutes
        context['puntos_itinerario'] = puntos_itinerario
        context['now'] = now
        context['posts'] = ultimos_post
        context['idiomas'] = idiomas

        return context


class AgendaDetailView(BaseContextMixin, DetailView):
    model = Agenda
    template_name = 'agenda/agenda.html'
    context_object_name = 'local_agenda'

    def get_object(self, queryset=None):
        # Obtener el objeto de la agenda utilizando el slug en lugar del ID
        slug = self.kwargs.get('slug')
        queryset = self.get_queryset()
        obj = get_object_or_404(queryset, slug=slug)
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Obtener el objeto actual
        current_object = self.get_object()
        now = timezone.now()
        show_ticket_section = False
        personalizacion = None
        personalizacion = Personalizacion.objects.filter().first()
        for variation in current_object.variationagenda_set.all():
            if now.date() <= variation.fecha:
                show_ticket_section = True
                break
        # Filtrar los eventos futuros utilizando objetos Q y obtener el primer objeto VariationAgenda de cada Agenda
        variation_agendas = VariationAgenda.objects.filter(
            Q(agenda__publicado=True)
        ).order_by('-fecha', '-hora')

        same_type_event = []
        future_events_near = []
        future_events_distant = []
        past_events = []

        for event in variation_agendas:
            if event.agenda.tipo_evento == current_object.tipo_evento:   
                same_type_event.append(event)
            elif event.fecha >= now.date():
                # Calcular la diferencia en días desde la fecha actual
                days_difference = (event.fecha - now.date()).days
                if days_difference <= 7:
                    future_events_near.append(event)  # Futuros cercanos
                else:
                    future_events_distant.append(event)  # Futuros lejanos
            else:
                past_events.append(event)

        # Concatenar los eventos agrupados en una lista plana en el orden deseado
        all_events = same_type_event + future_events_near + future_events_distant + past_events

        # coger el parallax de personalización

        parallax = Personalizacion.objects.filter().first()

        if parallax is not None:
            if parallax.parallax_agenda:
                parallax = parallax.parallax_agenda.parallax_agenda
            else:
                parallax = None
        else:
            parallax = None

        # Obtener la próxima variación más cercana
        next_variation = self.get_object().variationagenda_set.filter(fecha__gte=timezone.now()).order_by('fecha', 'hora').first()

        if next_variation:
            # Proporcionar la URL del archivo .ics en el contexto
            context['ics_slug_url'] = self.get_object().slug
            context['ics_variation_pk'] = next_variation.pk



        context['parallax'] = parallax
        context['coleccion_destacados'] = all_events[:20]
        context['link_tickets'] = show_ticket_section
        context['parallax'] = personalizacion.enlace_agenda
        
        return context

agenda/templates/agenda/selecciones/agenda_relacionada.html
{% load static %}
{% load i18n %}
{% if coleccion_destacados %}
<section class="container-fluid py-3 bg-light" id="destacats">
    <div class="py-3">
        <h4 class="related-activities-title text-center h2">{% blocktrans %}Activitats Relacionades{% endblocktrans %}</h4>
        <p class="lead related-activities-subtitle text-center">{% blocktrans %}Descobreix altres activitats interessants per a gaudir al màxim{% endblocktrans %}.</p>


    </div>
    <div class="swiper-container">
        <div class="swiper-wrapper">
            {% for agenda in coleccion_destacados %}
            <div class="swiper-slide">
                <a href="
                    {% if agenda.agenda %} 
                        {% url 'agenda:detalle_agenda' slug=agenda.agenda.slug %}
                    {% elif agenda.visitaguiada %}
                        {% url 'agenda:visites-guiades' slug=agenda.slug %}
                    {% elif agenda.mappoint %}
                        {% url 'map:mapa' slug=agenda.slug %}
                    {% else %}
                        {% spaceless %}
                            {{ agenda.get_absolute_url }}
                        {% endspaceless %}
                    {% endif %}" 
                class="related-activity-link">
                    
                    <div class="card related-activity-card mb-3 agenda-relacionada-container">
                        {% if agenda.agenda %}

                            {% with imagen=agenda.agenda.postgaleriaimagen_set.first %}
                                {% if imagen and imagen.imagen.archivo.url %}
                                    <div class="image-container image-container-agenda">
                                        <img src="{{ imagen.imagen.archivo.url }}" alt="{{ imagen.imagen.titulo }}" title="{{ imagen.imagen.titulo }}" class="img-fluid">
                                    </div>
                                {% endif %}
                            {% endwith %}

                        {% else %}

                            {% with imagen=agenda.postgaleriaimagen_set.first %}
                                {% if imagen and imagen.imagen.archivo.url %}
                                    <div class="image-container image-container-agenda">
                                        <img src="{{ imagen.imagen.archivo.url }}" title="{{ imagen.imagen.titulo }}" alt="{{ imagen.imagen.titulo }}" class="img-fluid">
                                    </div>
                                {% else %}
                                    {% with imagenPost=agenda.postimagen %}
                                        {% if imagenPost and imagenPost.imagen.archivo.url %}
                                            <div class="image-container image-container-agenda">
                                                <img src="{{ imagenPost.imagen.archivo.url }}" title="{{ imagenPost.imagen.titulo }}" alt="{{ imagenPost.imagen.titulo }}" class="img-fluid">
                                            </div>
                                        {% endif %}
                                    {% endwith %}
                                {% endif %}
                            {% endwith %}
                        {% endif %}
                        <div class="card-body text-center">
                            <h5 class="card-title related-activity-title">
                                {% if agenda.agenda %}
                                    {{ agenda.agenda.titulo }}
                                {% else %}
                                {{ agenda.titulo }}
                                {% endif %}
                            </h5>
                            <p class="card-text related-activity-description">
                                    {% if agenda.agenda %}
                                        {% if agenda.agenda.descripcion_corta|wordcount > 8 %}{{ agenda.agenda.descripcion_corta|truncatewords:5 }}...{% else %}{{ agenda.agenda.descripcion_corta }}{% endif %}
                                    {% else %}
                                        {% autoescape on %}
                                            {% if agenda.descripcion|wordcount > 15 %}{{ agenda.descripcion|truncatewords:10 |striptags |safe }}...{% else %}{{ agenda.descripcion |safe }}{% endif %}
                                        {% endautoescape %}
                                    {% endif %}
                                
                            </p>
                            {% if agenda.agenda %}
                            <div class="related-activity-details related-activity-details-agenda">
                                <p class="related-activity-date-time">
                                    <i class="fas fa-calendar-alt" style="color: #3ebfab;"></i>
                                    <span class="event-date">{{ agenda.fecha }}</span>
                                    <i class="fas fa-clock" style="color: #3ebfab;"></i>
                                    <span class="event-time">{{ agenda.hora }}</span><br>
                                    <i class="fas fa-map-marker-alt" style="color: #3ebfab;"></i> <span>{{ agenda.agenda.ubicacion.titulo }}</span>
                                </p>
                            </div>
                                {% if agenda.agenda.idiomas %}
                                    <div class="container-fluid text-center p-0 m-0" style="">
                                        {% for idioma in agenda.agenda.idiomas.all %}
                                            {% if idioma.nombre == 'es' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/es.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'cat' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/cat.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'en' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/en.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'fr' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/fr.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'it' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/it.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'de' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/de.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'pt' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/pt.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'ar' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/ar.svg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'fem' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/fem.jpg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'au' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/au.jpg' %}" height="25px" width="25px" />
                                            {% elif idioma.nombre == 'inc' %}
                                                <img class="img-fluid" src="{% static 'core/img/banderitas/inc.png' %}" height="25px" width="25px" />
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            {% elif agenda.visitaguiada %}
                                <div class="related-activity-details related-activity-details-agenda">
                                    <p class="related-activity-date-time">
                                        {% if agenda.publico_recomendado %}
                                            <i class="fas fa-users" style="color: #3ebfab;"></i>
                                            <span class="event-public">{{ agenda.get_publico_recomendado_display }}</span>
                                            <span class="px-2"></span>
                                        {% endif %}
                                        {% if agenda.fecha_inicio %}
                                            <i class="fas fa-calendar-alt" style="color: #3ebfab;"></i>
                                            <span class="event-date">{{ agenda.fecha_inicio }}</span>
                                            <span class="px-2"></span>
                                        {% endif %}
                                        {% if agenda.hora_inicio %}
                                            <i class="fas fa-clock" style="color: #3ebfab;"></i>
                                            <span class="event-time">{{ agenda.hora_inicio }}</span>
                                            <span class="px-2"></span>
                                        {% endif %}
                                        {% if agenda.precio == 0 %}
                                            <i class="fas fa-tag" style="color: #3ebfab;"></i>
                                            <span class="event-price">{% blocktrans %}Gratis{% endblocktrans %}</span>
                                        {% elif agenda.precio %}
                                            <i class="fas fa-tag" style="color: #3ebfab;"></i>
                                            <span class="event-price">{{ agenda.precio }} €</span>
                                        {% endif %}
                                    </p>
                                </div>
                            {% endif %}

                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>

        <div class="swiper-button-prev custom-prev"></div>
        <div class="swiper-button-next custom-next"></div>
    </div>
</section>

{% endif %}

{% block extra_script %}
<script>
    function initSwiper() {
        let swiper = new Swiper('.swiper-container', {
            loop: true,
            slidesPerView: 3, // Número de tarjetas por slide
            spaceBetween: 10, // Espacio entre tarjetas
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            breakpoints: {
                // Configuración para dispositivos móviles
                359:{
                    slidesPerView: 2
                },
                374:{
                    slidesPerView: 2,
                },

                767: {
                    slidesPerView: 3,
                },

                // Configuración para tablets
                991: {
                    slidesPerView: 3,
                },
            },
        });
    }
    document.addEventListener("DOMContentLoaded", function() {
        initSwiper();
    });
</script>
{% endblock extra_script %}