agenda/urls.py
from django.urls import path

from .views import PDFView, AgendaDetailView, VisitaGuiadaView, RutaView, ICSAgenda, DescargarPlaylist, GenerarRSS, AlojamientoView, RestauranteView, TurismeSostenibleView



app_name = 'agenda'

urlpatterns = [
    path('calendario/', PDFView.as_view(), name= 'calendario_pdf'),
    path('ics/', ICSAgenda.as_view(), name= 'agenda_ics'),
    path('descargar-playlist/', DescargarPlaylist.as_view(), name= 'descargar-audio'),
    path('visites-guiades/<slug:slug>/', VisitaGuiadaView.as_view(), name= 'visites-guiades'),
    path('ruta/<slug:slug>/', RutaView.as_view(), name= 'ruta'),
    path('descargar-playlist-rss/',GenerarRSS.as_view(), name= 'descargar-audio-rss'),
    path('allotjament/<slug:slug>/', AlojamientoView.as_view(), name= 'allotjament'),
    path('restaurant/<slug:slug>/', RestauranteView.as_view(), name="restaurant"),
    path('sostenibilitat/<slug:slug>/', TurismeSostenibleView.as_view(), name="turisme_sostenible"),
    path('<slug:slug>/', AgendaDetailView.as_view(), name= 'detalle_agenda'),
]

api/urls.py
from django.urls import path
from .views import TeenvioView
app_name = 'api'
urlpatterns = [
        path('newsletter/', TeenvioView.as_view(), name='newsletter'),
]

blog/urls.py
from django.urls import path
from .views import ListarPostsView, DetallePostView, ListarCategoria, ListarSubBlogView,DetalleSubBlogView, CategoriaDetailView, FiltrarAgendaView, DetalleNoticiaView, ListarNoticiaView, SubCategoriaDetailView, RestaurantAPI


app_name = 'blog'

urlpatterns = [
    path('posts/', ListarPostsView.as_view(), name='listar_posts'),
    path('post/<slug:slug>/', DetallePostView.as_view(), name='detalle_post'),
    path('categorias/', ListarCategoria.as_view(),name='listar_categoria'),
    path('c/<slug:slug>/', CategoriaDetailView.as_view(), name='categoria'),
    path('subblog/<slug:slug>/', DetalleSubBlogView.as_view(), name='detalle-subblog'),
    # API endpoints
    path('api/filtrar-agenda/', FiltrarAgendaView.as_view(), name='filtrar_agenda_api'),
    path('api/filtrar-restaurante/', RestaurantAPI.as_view(), name='filtrar_restaurante'),
    path('noticies/', ListarNoticiaView.as_view(), name="noticies"),
    path('n/<slug:slug>/', DetalleNoticiaView.as_view(), name='noticia'),
    path('subcategoria/<slug:slug>/', SubCategoriaDetailView.as_view(), name='subcategoria')
]

gaudeix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from multimedia_manager.urls import urlpatterns as url_media
#from multimedia_manager.filters import ImagenAutocomplete
from django.urls import re_path
from django_select2 import urls as select2_urls

from django.urls import path
from django.views.i18n import set_language

urlpatterns = [

    path('admin_gaudeix/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
    path('',include('blog.urls')),
    path('agenda/',include('agenda.urls')),
    path('map/',include('map.urls')),
    path('',include('personalizacion.urls')),
    path('', include('paginas_estaticas.urls')),
    path('s/', include('eventos_especiales.urls')),
    path('api/', include('api.urls')),
    path('sv/',include('subvenciones.urls')),
    path('c-d/', include('compra_y_descubre.urls')),
    path('idiomes/', include('django.conf.urls.i18n')),
    path('', include('traducciones.urls')),
    # re_path(
    #     r'^imagen-autocomplete/$',
    #     ImagenAutocomplete.as_view(),
    #     name='imagen-autocomplete',
    # ),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'core.views.error_404'
handler500 = 'core.views.error_500'

blog/forms.py
# En blog/forms.py

from django import forms
from .models import Categoria, Imagen
from dal import autocomplete
from .models import Categoria
from django.forms import ModelForm
from django.forms.widgets import TextInput



class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        widgets = {
            'subblog': autocomplete.ModelSelect2(url='subblog-autocomplete'),
        }

blog/views.py
from django.views.generic import ListView, DetailView
from .models import Post,SubBlog,Categoria, CategoriaBannerImagen, Noticia, SubCategoria
from agenda.models import Agenda, VisitaGuiada, Ruta, VariationAgenda, Alojamiento, Restaurante, VisionMision, TurismeSostenible
from map.models import MapPoint
from django.http import JsonResponse
from django.views.generic import View
from core.mixin.base import BaseContextMixin
from redes_sociales.models import RedSocial
from .utils import agrupar_eventos_por_dia, serialize_restaurante_to_json
from django.db.models import Q
import json
from django.shortcuts import get_object_or_404
from django.utils import timezone
from eventos_especiales.models import EventoEspecial
from personalizacion.models import Personalizacion
from multimedia_manager.models import Parallax
from django.core.serializers import serialize
from django.shortcuts import redirect

from django.http import JsonResponse

class ListarPostsView(ListView):
    """
    Vista basada en clase para listar todos los posts.
    Utiliza una plantilla 'listar_posts.html' para mostrar la lista de posts.
    """
    model = Post  # Modelo que se utilizará para obtener los posts
    template_name = 'blog/post/listar_posts.html'  # Plantilla HTML para la página
    context_object_name = 'posts'  # Nombre con el que se pasará la lista de posts a la plantilla

    def get_queryset(self):
        """
        Devuelve la queryset de posts filtrada para mostrar solo los publicados.
        """
        queryset = super().get_queryset().filter(publicado=True)
        return queryset

class DetallePostView(BaseContextMixin, DetailView):
    """
    Vista basada en clase para mostrar los detalles de un post específico.
    Utiliza una plantilla 'detalle_post.html' para mostrar los detalles.
    """
    model = Post  # Modelo que se utilizará para obtener el post
    template_name = 'blog/post/detalle_post.html'  # Plantilla HTML para la página
    context_object_name = 'post'  # Nombre con el que se pasará el objeto post a la plantilla

    def get_context_data(self, **kwargs):
        """
        Agrega datos adicionales al contexto de la plantilla.
        """
        context = super().get_context_data(**kwargs)
        # Puedes agregar aquí cualquier dato adicional que quieras pasar a la plantilla
        return context


class ListarSubBlogView(ListView):
    """
    Vista basada en clase para listar los subblogs publicados.
    Utiliza una plantilla 'listar_subblog.html' para mostrar la lista de subblogs.
    """
    model = SubBlog  # Modelo que se utilizará para obtener los subblogs
    template_name = 'blog/subblog/listar_subblog.html'  # Plantilla HTML para la página
    context_object_name = 'blogs'  # Nombre con el que se pasará la lista de subblogs a la plantilla

    def get_queryset(self):
        """
        Devuelve la queryset de subblogs filtrada para mostrar solo los publicados.
        """
        queryset = super().get_queryset().filter(publicado=True)
        return queryset


class DetalleSubBlogView(BaseContextMixin, DetailView):
    """
    Vista basada en clase para mostrar los detalles de un subblog específico.
    Utiliza una plantilla 'detalle_subblog.html' para mostrar los detalles.
    """
    model = SubBlog  # Modelo que se utilizará para obtener el subblog
    template_name = 'blog/subblog/detalle_subblog.html'  # Plantilla HTML para la página
    context_object_name = 'subblog'  # Nombre con el que se pasará el objeto subblog a la plantilla
    pk_url_kwarg = 'subblog_id'  # Nombre del argumento de URL para identificar el subblog

    def get_context_data(self, **kwargs):
        """
        Agrega datos adicionales al contexto de la plantilla.
        """
        context = super().get_context_data(**kwargs)
        subblog_actual = self.object
        # Filtrar y agregar las categorías relacionadas con el subblog actual al contexto
        context['categorias'] = Categoria.objects.filter(subblog=subblog_actual)
        return context


class CategoriaDetailView(BaseContextMixin, DetailView):
    """
    Vista basada en clase para mostrar los detalles de una categoría específica.
    Utiliza una plantilla 'detalle_categoria.html' para mostrar los detalles.
    """
    model = Categoria # Modelo que se utilizará para obtener la categoría
    template_name = 'blog/categorias/detalle_categoria.html' # Plantilla HTML para la página
    context_object_name = 'categoria' # Nombre con el que se pasará el objeto categoría a la plantilla
    pk_url_kwarg = 'categoria_id' # Nombre del argumento de URL para identificar la categoría


    def get(self, request, *args, **kwargs):
        """
        Agrega datos adicionales al contexto de la plantilla.
        """
        
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        categoria = self.object

        categorias_hermanas = Categoria.objects.filter(publicado= True).exclude(id=categoria.id)
        context['categorias'] = categorias_hermanas
        now = timezone.now()
        subcategorias = categoria.subcategorias.filter(publicado=True)


        # Verificar si el tipo de categoría es "agenda"
        if categoria.tipo == 'agenda':
            # Si la categoría es de tipo 'agenda', obtener la lista de agendas relacionadas
            agendas = Agenda.objects.filter(publicado=True).all()
            parallax = None
            carrusel = None
            personalizacion = Personalizacion.objects.filter().first()

            if personalizacion is not None:
                if personalizacion.carrusel_agenda:
                    carrusel = personalizacion.carrusel_agenda
                elif personalizacion.parallax_agenda:
                    parallax = personalizacion.parallax_agenda.parallax_agenda
                else:
                    parallax = None
            else:
                parallax = Parallax.objects.filter().first()
            
            redes_sociales= RedSocial.objects.filter().all()
            categorias = Categoria.objects.filter(publicado=True)
            context['redes_sociales'] = redes_sociales
            context['parallax'] = parallax
            context['carrusel'] = carrusel
            context['agendas'] = agendas
            context['joves'] = VariationAgenda.objects.filter(agenda__publicado= True, agenda__tipo_evento='joves',fecha__gt=now).first()
            context['categorias'] = categorias

        elif categoria.tipo == 'visitas_guiadas':
            # Si la categoría es de tipo 'visitas_guiadas', obtener las visitas guiadas relacionadas
            visitas_guiadas = VisitaGuiada.objects.filter(publicado=True, categoria = categoria).all()
            if visitas_guiadas.count() ==1 and categoria.mostrar_primer_hijo:
                return redirect('agenda:visites-guiades',slug = visitas_guiadas.first().slug)
            elif subcategorias.count() == 1 and categoria.mostrar_primer_hijo:
                return redirect('blog:subcategoria', slug=subcategorias.first().slug)
            context['visitas_guiadas'] = visitas_guiadas


        elif categoria.tipo == 'noticies':
            # Si la categoría es de tipo 'noticias', obtener las noticias relacionadas
            noticias = Noticia.objects.filter(publicado=True, categoria=categoria).all()
            context['noticias'] = noticias

        elif categoria.tipo == 'senderisme':
            # Si la categoría es de tipo 'senderisme', obtener las rutas relacionadas
            rutes  = Ruta.objects.filter(publicado=True).all()
            if rutes.count() == 1 and categoria.mostrar_primer_hijo:
                return redirect('agenda:ruta', slug = rutes.first().slug)
            elif subcategorias.count() == 1:
                return redirect('blog:subcategoria', slug=subcategorias.first().slug)
            
            context['rutes'] = rutes

        elif categoria.tipo == 'allotjament':
            alojamientos = Alojamiento.objects.filter(publicado=True, categoria=categoria).all()
            context['alojamientos'] = alojamientos
            if alojamientos.count() == 1 and categoria.mostrar_primer_hijo:
                return redirect('agenda:allotjament', slug = alojamientos.first().slug)
            elif subcategorias.count() == 1:
                return redirect('blog:subcategoria', slug=subcategorias.first().slug)
            
            posts = Post.objects.filter(publicado = True, categoria = categoria).exclude(alojamiento__isnull=False)
            context['posts'] = posts

        elif categoria.tipo == 'restaurant':
            restaurantes = Restaurante.objects.filter(publicado=True, categoria=categoria).all()
            context['restaurantes'] = restaurantes

            if restaurantes.count() == 1 and categoria.mostrar_primer_hijo:
                return redirect('agenda:restaurant', slug = restaurantes.first().slug)
            elif subcategorias.count() == 1:
                return redirect('blog:subcategoria', slug=subcategorias.first().slug)
            
            posts = Post.objects.filter(publicado = True, categoria = categoria).exclude(restaurante__isnull=False)
            context['posts'] = posts
            
        elif categoria.tipo == 'normal':
            # Si la categoría es de tipo 'normal', obtener los posts relacionados
            posts = Post.objects.filter(publicado = True, categoria = categoria).all()
            if posts.count() == 1 and categoria.mostrar_primer_hijo:
               return redirect('blog:detalle_post', slug = posts.first().slug)
            elif subcategorias.count() == 1:
                return redirect('blog:subcategoria', slug=subcategorias.first().slug)
            context['posts'] = posts

        elif categoria.tipo == 'lloc':
            # Si la categoría es de tipo 'lloc', obtener los posts relacionados
            llocs = MapPoint.objects.filter(publicado = True, categoria = categoria)
            context['llocs'] = llocs

blog/templates/blog/categorias/agenda_utils/agenda_portada.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block meta_description %}
  {% if categoria.metadescripcion %}
    <meta name="Description" content="{{ categoria.metadescripcion | safe | striptags }}">
    <meta property="og:description" content="{{ categoria.metadescripcion | safe | striptags }}">
  {% else %}
    {% if categoria.descripcion %}
      <meta name="Description" content="{{ categoria.descripcion | safe | striptags | truncatewords_html:150 }}">
      <meta property="og:description" content="{{ categoria.descripcion | striptags | truncatewords_html:150 | safe }}">
    {% endif %}
  {% endif %}
{% endblock meta_description%}

{% block meta_keywords %}
  {% if categoria.tags.all %}
    <meta name="Keywords" content="{% for tag in categoria.tags.all %}{{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}">
  {% endif %}
{% endblock meta_keywords %}

{% block canonical %}
  <link rel="canonical" href="{{ canonical_url }}"/>
{% endblock canonical %}

{% block title %}
    {% autoescape off %}
        {{ categoria.titulo |striptags | safe  }}
    {% endautoescape %}
{% endblock title %}


{% block extra_css %}
<style>
    .spinner-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background-color: rgba(255, 255, 255, 0.8);
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 9999;
    }
    
    .spinner {
        border: 4px solid rgba(0, 0, 0, 0.3);
        border-top: 4px solid {% if header %} {{header.color_fondo_header}} {% else %} #3498db {% endif %}  ;
        border-radius: 50%;
        width: 40px;
        height: 40px;
        animation: spin 1s linear infinite;
    }
    
    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
  


  @media only screen and (max-width: 767px) {
    div#calendar-agenda-gaudeix{
      display:none;
    }
    #tipo-evento {
      text-align: center;
    }
  }
</style>

{% endblock extra_css %}

{% block content %}
<section class="p-lg-5 p-md-5 overflow-hidden">
  <div class="col-12">
    <h1 class="h1 text-center py-5">{% blocktrans %}Viu la Cultura i les Festes a Cabrera de Mar{% endblocktrans %}</h1>
  </div>
  {% include 'blog/categorias/agenda_utils/filtro_agenda.html' %}
</section>

{% endblock %}

{% block asides %}
<aside class="container-fuild agenda-pdf-link py-2 my-2">
  <div class="col-md-12 col-lg-12 agenda-special-categories p-5">
      <div class="text-center  m-0 p-2 bg-light agenda-pdf-link">
          <a href="{% url 'agenda:calendario_pdf' %}" class="btn btn-outline-dark btn-lg">
              <i class="fas fa-file-download"></i>
              {% blocktrans %}Descarrega tota l'agenda en PDF{% endblocktrans %}
          </a>
      </div>
  </div>
</aside>
  {% if carrusel %}
    <div class="hero-agenda-especial py-3">
      {% comment %} Verifica si es un dispositivo móvil y el rango de imágenes {% endcomment %}
      {% if not request.user_agent.is_pc and carrusel.imatges.all.count >= 5 and carrusel.imatges.all.count <= 10 %}
        {% comment %} Asumiendo que deseas el carrusel estándar para dispositivos móviles {% endcomment %}
        {% include 'carrusel/carrusel.html' %}
      {% else %}
        {% if carrusel.tipo == 'collage' %}
          {% include 'carrusel/collage.html' %}
        {% else %}
          {% include 'carrusel/carrusel.html' %}
        {% endif %}
      {% endif %}
    </div>
  {% else %}
    {% if parallax %}
      <div class="hero-agenda-especial py-3">
        {% include 'parallax/parallax.html' %}
      </div>
    {% endif %}
  {% endif %}


  {% if categorias %}
    <aside class="container-fuild py-0 my-0">
      <div class="container">
        <div class="col-12">
          <h2 class="text-center h2">{% blocktrans %}Descobreix els Tresors de Cabrera de Mar{% endblocktrans %}</h2>
        </div>
      </div>
    </aside>
    {% include 'blog/selecciones/categorias_seleccion.html' %}
  {% endif %}
{% endblock asides %}